"""Initial database schema with HistoricalData

Revision ID: a1a712c0eb2b
Revises: 
Create Date: 2025-09-13 21:06:14.251641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a712c0eb2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_data',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('is_valid_data', sa.Boolean(), nullable=False),
    sa.Column('trading_hours', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('simulation_entry_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('simulation_stop_loss', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('simulation_take_profit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('simulation_shares', sa.Integer(), nullable=True),
    sa.Column('simulation_pnl', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('simulation_executed', sa.Boolean(), nullable=False),
    sa.Column('market_phase', sa.String(length=20), nullable=True),
    sa.Column('volatility_score', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('indicators_data', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_data_symbol'), 'historical_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_historical_data_timestamp'), 'historical_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_data_timestamp'), table_name='historical_data')
    op.drop_index(op.f('ix_historical_data_symbol'), table_name='historical_data')
    op.drop_table('historical_data')
    # ### end Alembic commands ###
